trigger:
  - main

pool:
  name: 'Default'

steps:

- task: Maven@4
  displayName: 'Compilar y ejecutar pruebas unitarias (OrderDiscountCalculatorTest)'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'test'
    options: '-Dtest=OrderDiscountCalculatorTest'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'HostSystem'

- task: PublishTestResults@2
  displayName: 'Publicar resultados de prueba'
  condition: always()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'OrderDiscountCalculator - Pruebas Unitarias'